#!/bin/sh
set -e
# Disable user namespace if we're not in a container
if ! systemd-detect-virt -c; then
    echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
fi
dpkg-buildpackage -rfakeroot -us -uc -b
